### PR TITLE
Instantiate the ErrorBuffer directly

### LINKED ISSUE #755: BindingResolutionException while building ErrorBuffer, occurs when using xDebug
I get the following error when I am trying to debug the code executed through a graphql query or mutation with xdebug:

Exception has occurred.
Illuminate\Contracts\Container\BindingResolutionException: Target [Closure] is not instantiable while building [Nuwave\Lighthouse\Execution\ErrorBuffer].

This only happens if the debugger has to go through graphql (lighthouse) otherwise it works fine (meaning I can debug the code and does not get stopped at the above-mentioned error). I tried it on an existing project and on a completely new and clean install of everything.

The clean install had the following:
- OS: Windows 10
- Laravel: v5.8.14
- PHP: v7.3.4 NTS x64
- XDebug: v2.7.1 NTS
- Lighthouse-PHP: v3.4.0

The clean install hasn't had a single line of custom code, I only used what I got with the installs (user queries and default routes).

Please help me fix this issue, thank you!

### PR DESCRIPTION
**Pull request by spawnia**
This avoids unnecessary calls into the container and fixes a bug that prevented
its instantiation.

Resolves #755 ~~(hopefully)~~ definitely!

### CODE REVIEW

File: src/Schema/Factories/FieldFactory.php [hunk 1]
```diff
@@ -169,7 +169,7 @@ function (FieldValue $fieldValue): FieldValue {
             function () use ($argumentValues, $resolverWithMiddleware) {
                 $this->setResolverArguments(...func_get_args());
 
-                $this->validationErrorBuffer = app(ErrorBuffer::class)->setErrorType('validation');
+                $this->validationErrorBuffer = (new ErrorBuffer())->setErrorType('validation');
```
Comment (lucasmichot) [inline src/Schema/Factories/FieldFactory.php]:
```suggestion
                $this->validationErrorBuffer = (new ErrorBuffer)->setErrorType('validation');
```
