### PR TITLE
Fix cursor pagination always returning the first page when no fields from the `pageInfo` are requested

### LINKED ISSUE #2189: `CONNECTION` pagination broken without `pageInfo`
**Describe the bug**

CONNECTION pagination offset doesn't work as expected if no pageInfo is requested. Attribute `after` looks not being used, and page 1 is returned when asking for page 2

I added 2 similar unit tests is [this commit](https://github.com/pyrou/lighthouse/commit/c1609c4ecfe1a736b6a1dd328d3c273707e9a8bb), one with pageInfo, one without. Second test is failing, items for page one is returned.

**Lighthouse Version**

This issue introduced with PR #2170 (Lighthouse 5.55)

### PR DESCRIPTION
**Pull request by stayallive**
- [x] Added or updated tests
- [x] ~Documented user facing changes~
- [x] Updated CHANGELOG.md

Fixes #2189

**Changes**

We calculate an optimal pagination strategy when the paginator info is not requested. But since cursor based pagination needs some special handling to correctly calculate the correct page to retrieve the `PaginationArgs::extractArgs` needs to get the original pagination type instead of the optimal type. We can change the type to the optimal one when applying it to the builder keeping the benefits but fixing the bug :)

Thanks @pyrou for finding and reporting the bug and creating the failing tests!

**Breaking changes**

None.

### CODE REVIEW

File: tests/Integration/Pagination/PaginateDirectiveDBTest.php [hunk 1]
```diff
@@ -595,6 +596,112 @@ public function testQueriesConnectionWithoutPageInfo(): void
...
+            users: [User!]! @paginate(type: CONNECTION)
+        }
+        ';
+
+        $cursor = Cursor::encode(2);
+
+        $this->assertQueryCountMatches(2, function () use ($users, $cursor): void {
+            $this->graphQL(/** @lang GraphQL */ "
+            {
+                users(first: 2, after: \"{$cursor}\") {
```
Comment (spawnia) [inline tests/Integration/Pagination/PaginateDirectiveDBTest.php:618]: Should use variables

File: tests/Integration/Pagination/PaginateDirectiveDBTest.php [hunk 2]
```diff
@@ -595,6 +596,112 @@ public function testQueriesConnectionWithoutPageInfo(): void
...
+            users: [User!]! @paginate(type: CONNECTION)
+        }
+        ';
+
+        $cursor = Cursor::encode(2);
+
+        $this->assertQueryCountMatches(1, function () use ($users, $cursor): void {
+            $this->graphQL(/** @lang GraphQL */ "
+            {
+                users(first: 2, after: \"{$cursor}\") {
```
Comment (spawnia) [inline tests/Integration/Pagination/PaginateDirectiveDBTest.php:681]: Also should use variables

**Review by spawnia — CHANGES_REQUESTED** [review]
Nicely done, just needs a stylistic fix.

**Comment by stayallive** [comment]
You are right, I was being lazy here... fixed!
