### PR TITLE
@can directive improvements

### LINKED ISSUE #2225: `@can`: Properly support `denyAsNotFound` or equivalent Auth responses from Policies and Gates
**What problem does this feature proposal attempt to solve?**

This feature would be required to prevent model existence leakage security issues from the `@can` directive.

Currently, if a field is marked with `@can(resolve: true)`, the policy is not checked for `null` results from resolvers. This can actually be fine, but when they are checked for non-null results, Lighthouse has now leaked the models existence. It doesn't matter if the policy responded with a `Response::denyAsNotFound()`.

It is also likely `@can(query)` and `@can(find)` suffer from this issue as well.

**Which possible solutions should be considered?**

If a policy is checked against any model instance, the result should be replaced with `null` if the result of `Response::denyAsNotFound()` or the like is returned from the policy. It could also be appropriate to filter out any items from resolvers that return collections of items when this response is received for any given item.

The only work-around right now is to replace the `@can` directive with a local implementation aware of this type of response, but the complexity of the `@can` directive makes that an issue. Especially when upgrading to new version of Lighthouse and trying to keep things in sync with the root.

See this article for a discussion on this security issue:
https://larasec.substack.com/p/security-tip-leaking-model-existence

### LINKED ISSUE #2453: `@can` directive improvements
The PR https://github.com/nuwave/lighthouse/pull/2452 solves one of `@can` directive problems, but it has some more problems which makes it unusable for me:

1. It accepts only Eloquent models. So I can't use it on my Doctrine models, which are just plain objects. 
```php
protected function authorize(Gate $gate, string|array $ability, string|Model|null $model, array $arguments): void
```

2. Checking global gates (without model/policy). It looks like this
```php
Gate::define('admin', fn (User $user) => $user->isAdmin()
```
```graphql
query {
    sensitiveInfo:SensitiveInfo!  @can(ability:"admin") 
}
```

3. It always throws 403 error. I have a lot of fields which must be concealed for non-authorized user. Keeping in mind https://github.com/nuwave/lighthouse/issues/2225 we might add a parameter like this:

```graphql
  """
  Action to do if the user is not authorized.
  """
  action: CanAction! = EXCEPTION_NOT_AUTHORIZED

enum CanAction {
    EXCEPTION_NOT_AUTHORIZED
    EXCEPTION_NOT_FOUND
    RETURN_NULL
    RETURN_ZERO
    RETURN_FALSE
    RETURN_EMPTY_STRING
}
```

4. We have too many mutually exclusive parameters. It might be a good time to divide them to `@canQuery`, `@canFind`, `@canResolved` and `@canRoot`

### PR DESCRIPTION
**Pull request by k0ka**
Resolves #2453
Resolves #2225
 
- [x] Added or updated tests
- [x] Documented user facing changes
- [x] Updated CHANGELOG.md

**Changes**

- Split up `@can` directive into `@canFind`, `@canModel`, `@canQuery`, `@canResolved` and `@canRoot`
- Added `action` and `return_value` arguments to `@can*` family of directives 
- Allows using any objects in `@can*` family of directives

**Breaking changes**

The `@can` directive is deprecated and would be removed in the next major update.

### CODE REVIEW

File: tests/Unit/Auth/CanDirectiveTestBase.php [hunk 1]
```diff
@@ -0,0 +1,182 @@
...
+    }
+
+    public function testThrowsWithCustomMessageIfNotAuthorized(): void
+    {
+        $this->be(new User());
+
+        $this->schema = $this->getSchema('ability: "superAdminOnly"');
+
+        $this
+            ->graphQL($this->getQuery())
```
Comment (spawnia) [inline tests/Unit/Auth/CanDirectiveTestBase.php:43]: This can be combined

File: tests/Unit/Auth/CanModelDirectiveTest.php [hunk 2]
```diff
@@ -0,0 +1,23 @@
+<?php declare(strict_types=1);
+
+namespace Auth;
+
+use Tests\Unit\Auth\CanDirectiveTestBase;
+
+class CanModelDirectiveTest extends CanDirectiveTestBase
```
Comment (spawnia) [inline tests/Unit/Auth/CanModelDirectiveTest.php:7]: final

File: tests/Unit/Auth/CanRootDirectiveTest.php [hunk 3]
```diff
@@ -0,0 +1,180 @@
...
+    protected function getQuery(): string
+    {
+        return /** @lang GraphQL */ '
+            query ($foo: String) {
+                user {
+                    name (foo: $foo)
+                }
+            }
+        ';
+    }
```
Comment (spawnia) [inline tests/Unit/Auth/CanRootDirectiveTest.php:35]: repeats parent?

**Review by spawnia — CHANGES_REQUESTED** [review]
Thanks for starting this.

File: CHANGELOG.md [hunk 4]
```diff
@@ -9,6 +9,11 @@ You can find and compare releases at the [GitHub release page](https://github.co
 
 ## Unreleased
 
+- `@can` directive improvements https://github.com/nuwave/lighthouse/pull/2483
+-- Split up `@can` directive into `@canFind`, `@canModel`, `@canQuery`, `@canResolved` and `@canRoot`
+-- Added `action` and `return_value` arguments to `@can*` family of directives 
+-- Allows using any objects in `@can*` family of directives
```
[the remark this answers is not in the document]
Comment (k0ka) [reply CHANGELOG.md]: change to plain list

File: UPGRADE.md [hunk 5]
```diff
@@ -24,6 +24,15 @@ It will prevent the following type of HTTP requests:
 - `GET` requests
 - `POST` requests that can be created using HTML forms
 
+### `@can` directive is replaced with `@can*` directives
+
+The `@can` directive was removed in favor of more specialized directives:
```
[the remark this answers is not in the document]
Comment (k0ka) [reply UPGRADE.md:29]: added some examples how directive would be changed in some cases from our documentation and tests.

File: docs/master/api-reference/directives.md [hunk 6]
```diff
@@ -604,109 +604,155 @@ You can find usage examples of this directive in [the caching docs](../performan
...
+"""
+Statically defined arguments that are passed to `Gate::check`.
 
-  Mutually exclusive with `query`, `find`, and `root`.
-  """
-  resolved: Boolean! = false
+You may pass arbitrary GraphQL literals,
+e.g.: [1, 2, 3] or { foo: "bar" }
+"""
+args: CanArgs or : [CanArgs]
```
[the remark this answers is not in the document]
Comment (k0ka) [reply docs/master/api-reference/directives.md]: Yep, I already deleted in code, forgot to update documentation. Fixed it.

File: src/Auth/CanResolvedDirective.php [hunk 7]
```diff
@@ -0,0 +1,62 @@
...
+
+                return $modelLike;
+            },
+        );
+    }
+
+    public function manipulateFieldDefinition(DocumentAST &$documentAST, FieldDefinitionNode &$fieldDefinition, ObjectTypeDefinitionNode|InterfaceTypeDefinitionNode &$parentType): void
+    {
+        if ($parentType->name->value === RootType::MUTATION) {
+            throw new DefinitionException("Do not use @can with `resolved` on mutation {$fieldDefinition->name}->value, it is unsafe as the resolver will run before checking permissions. Use `query` or `find`.");
```
[the remark this answers is not in the document]
Comment (k0ka) [reply src/Auth/CanResolvedDirective.php]: Updated the error to 
```php
"Do not use @canResolved on mutation {$fieldDefinition->name->value}, it is unsafe as the resolver will run before checking permissions. Use `@canFind` or `@canQuery` instead."
```

File: tests/Integration/Auth/CanFindDirectiveDBTest.php [hunk 8]
```diff
@@ -0,0 +1,364 @@
...
+        $admin = new User();
+        $admin->name = UserPolicy::ADMIN;
+        $this->be($admin);
+
+        $user = factory(User::class)->create();
+        assert($user instanceof User);
+
+        $this->schema = /** @lang GraphQL */ '
+        type Query {
+            user(id: ID @eq): User
```
[the remark this answers is not in the document]
Comment (k0ka) [reply tests/Integration/Auth/CanFindDirectiveDBTest.php]: Changed all `ID @eq ` to `ID @whereKey` in Can*DBTest

File: tests/Unit/Auth/CanRootDirectiveTest.php (hunk 3 above)
Comment (k0ka) [reply tests/Unit/Auth/CanRootDirectiveTest.php:35]: No. 
In CanRoot we apply argument to field `name`, not to query `user`. Otherwise test with `injectArgs: true` won't work.

File: src/Auth/BaseCanDirective.php [hunk 9]
```diff
@@ -0,0 +1,157 @@
...
+  action: CanAction! = EXCEPTION_PASS
+
+  """
+  Value to return if the user is not authorized and `action` is `RETURN_VALUE`.
+  """
+  return_value: CanArgs
+GRAPHQL;
+    }
+
+    public static function definition(): string
```
[the remark this answers is not in the document]
Comment (k0ka) [reply src/Auth/BaseCanDirective.php:53]: I added common types to `definition` so they would be included only once to ide helper. Common directive arguments are included into `commonArguments`.

File: CHANGELOG.md [hunk 10]
```diff
@@ -9,6 +9,10 @@ You can find and compare releases at the [GitHub release page](https://github.co
 
 ## Unreleased
 
+- Split up `@can` directive into `@canFind`, `@canModel`, `@canQuery`, `@canResolved` and `@canRoot` https://github.com/nuwave/lighthouse/pull/2483
+- Added `action` and `return_value` arguments to `@can*` family of directives https://github.com/nuwave/lighthouse/pull/2483
```
Comment (spawnia) [inline CHANGELOG.md:13]: We use `camelCase` for directive arguments.

File: UPGRADE.md [hunk 11]
```diff
@@ -24,6 +24,36 @@ It will prevent the following type of HTTP requests:
...
+- if none of the above are set: `@canModel`
+
+```diff
+type Mutation {
+-   createPost(input: PostInput): Post @can(ability: "create")
++   createPost(input: PostInput): Post @canModel(ability: "create")
+-   editPost(input: PostInput): Post @can(find: "input.id", ability: "edit")
++   editPost(input: PostInput): Post @canFind(find: "input.id", ability: "edit")
+-   deletePosts(ids: [ID!]! @whereKey): [Post!]! @can(query: true, ability: "delete") @delete
++   deletePosts(ids: [ID!]! @whereKey): [Post!]! @canQuery(ability: "delete") @delete
```
Comment (spawnia) [inline UPGRADE.md:43]:
```suggestion
-   createPost(input: PostInput! @spread): Post! @can(ability: "create") @create
+   createPost(input: PostInput! @spread): Post! @canModel(ability: "create") @create
-   updatePost(input: PostInput! @spread): Post! @can(find: "input.id", ability: "edit") @update
+   updatePost(input: PostInput! @spread): Post! @canFind(find: "input.id", ability: "edit") @update
-   deletePosts(ids: [ID!]! @whereKey): [Post!]! @can(query: true, ability: "delete") @delete
+   deletePosts(ids: [ID!]! @whereKey): [Post!]! @canQuery(ability: "delete") @delete
```

File: docs/master/api-reference/directives.md [hunk 12]
```diff
@@ -604,109 +604,155 @@ You can find usage examples of this directive in [the caching docs](../performan
...
+action: CanAction! = EXCEPTION_PASS
 
-  """
-  Pass along the client given input data as arguments to `Gate::check`.
-  """
-  injectArgs: Boolean! = false
+"""
+Value to return if the user is not authorized and `action` is `RETURN_VALUE`.
+"""
+return_value: CanArgs
```
Comment (spawnia) [inline docs/master/api-reference/directives.md:641]:
```suggestion
returnValue: CanArgs
```

File: docs/master/api-reference/directives.md [hunk 13]
```diff
@@ -604,109 +604,155 @@ You can find usage examples of this directive in [the caching docs](../performan
...
+    """
+    Throw generic "not authorized" exception to conceal the real error.
+    """
+    EXCEPTION_NOT_AUTHORIZED
 
-  Mutually exclusive with `resolved`, `find`, and `root`.
-  """
-  query: Boolean! = false
+    """
+    Return the value specified in `value` argument to conceal the real error.
```
Comment (spawnia) [inline docs/master/api-reference/directives.md:664]:
```suggestion
    Return the value specified in `returnValue` argument to conceal the real error.
```

File: docs/master/security/authorization.md [hunk 14]
```diff
@@ -86,18 +86,43 @@ final class PostPolicy
...
-For some models, you may want to restrict access for specific instances of a model.
-Set the `resolved` argument to `true` to have Lighthouse check permissions against
-the resolved model instances.
+You can also protect specific models by using the [@canFind](../api-reference/directives.md#canfind) 
+or [@canQuery](../api-reference/directives.md#canquery) directive.
+They will query the database and check the specified policy against the result.
+
+```graphql
+type Mutation {
+  editPost(input: PostInput): Post @canFind(ability: "edit", find: "input.id")
```
Comment (spawnia) [inline docs/master/security/authorization.md:97]:
```suggestion
  updatePost(input: UpdatePostInput! @update): Post! @canFind(ability: "edit", find: "input.id") @update
```

File: docs/master/security/authorization.md [hunk 15]
```diff
@@ -86,18 +86,43 @@ final class PostPolicy
...
+}
+
+input PostInput {
+    id: ID!
```
Comment (spawnia) [inline docs/master/security/authorization.md:101]:
```suggestion
    id: ID!
    title: String
    
```

File: src/Auth/CanResolvedDirective.php [hunk 16]
```diff
@@ -0,0 +1,62 @@
...
+{$commonArguments}
+) repeatable on FIELD_DEFINITION
+GRAPHQL;
+    }
+
+    protected function authorizeRequest(mixed $root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo, callable $resolver, callable $authorize): mixed
+    {
+        return Resolved::handle(
+            $resolver($root, $args, $context, $resolveInfo),
+            function ($modelLike) use ($authorize) {
```
Comment (spawnia) [inline src/Auth/CanResolvedDirective.php:42]:
```suggestion
            function (Paginator|iterable|Model $modelLike) use ($authorize): Paginator|iterable|Model {
```

File: src/Auth/CanResolvedDirective.php [hunk 17]
```diff
@@ -0,0 +1,62 @@
...
+
+                return $modelLike;
+            },
+        );
+    }
+
+    public function manipulateFieldDefinition(DocumentAST &$documentAST, FieldDefinitionNode &$fieldDefinition, ObjectTypeDefinitionNode|InterfaceTypeDefinitionNode &$parentType): void
+    {
+        if ($parentType->name->value === RootType::MUTATION) {
+            throw new DefinitionException("Do not use @canResolved on mutation {$fieldDefinition->name->value}, it is unsafe as the resolver will run before checking permissions. Use `@canFind` or `@canQuery` instead.");
```
Comment (spawnia) [inline src/Auth/CanResolvedDirective.php:59]:
```suggestion
            throw new DefinitionException("Do not use @canResolved on mutation {$fieldDefinition->name->value}, it is unsafe as the resolver will run before checking permissions. Use @canFind or @canQuery instead.");
```

File: tests/Integration/Auth/CanFindDirectiveDBTest.php [hunk 18]
```diff
@@ -0,0 +1,364 @@
...
+        $admin = new User();
+        $admin->name = UserPolicy::ADMIN;
+        $this->be($admin);
+
+        $user = factory(User::class)->create();
+        assert($user instanceof User);
+
+        $this->schema = /** @lang GraphQL */ '
+        type Query {
+            user(id: ID @whereKey): User
```
Comment (spawnia) [inline tests/Integration/Auth/CanFindDirectiveDBTest.php:26]:
```suggestion
            user(id: ID! @whereKey): User
```

File: tests/Integration/Auth/CanFindDirectiveDBTest.php [hunk 19]
```diff
@@ -0,0 +1,364 @@
...
+        $user->name = UserPolicy::ADMIN;
+        $this->be($user);
+
+        $this->mockResolverExpects(
+            $this->never(),
+        );
+
+        $this->schema = /** @lang GraphQL */ '
+        type Query {
+            user(id: ID @whereKey): User
```
Comment (spawnia) [inline tests/Integration/Auth/CanFindDirectiveDBTest.php:65]:
```suggestion
            user(id: ID! @whereKey): User
```

File: tests/Integration/Auth/CanFindDirectiveDBTest.php [hunk 20]
```diff
@@ -0,0 +1,364 @@
...
```
Comment (spawnia) [inline tests/Integration/Auth/CanFindDirectiveDBTest.php:105]:
```suggestion
            user(id: ID! @whereKey): User
```

File: tests/Integration/Auth/CanFindDirectiveDBTest.php [hunk 21]
```diff
@@ -0,0 +1,364 @@
...
+    {
+        $user = new User();
+        $user->name = UserPolicy::ADMIN;
+        $this->be($user);
+
+        $this->mockResolver(null);
+
+        $this->schema = /** @lang GraphQL */ '
+        type Query {
+            user(id: ID @whereKey): User
```
Comment (spawnia) [inline tests/Integration/Auth/CanFindDirectiveDBTest.php:143]:
```suggestion
            user(id: ID! @whereKey): User
```

File: tests/Integration/Auth/CanFindDirectiveDBTest.php [hunk 22]
```diff
@@ -0,0 +1,364 @@
...
+
+    public function testFindUsingNestedInputWithDotNotation(): void
+    {
+        $user = factory(User::class)->create();
+        assert($user instanceof User);
+        $this->be($user);
+
+        $this->schema = /** @lang GraphQL */ '
+        type Query {
+            user(input: FindUserInput): User
```
Comment (spawnia) [inline tests/Integration/Auth/CanFindDirectiveDBTest.php:201]:
```suggestion
            user(input: FindUserInput!): User
```

File: tests/Integration/Auth/CanResolvedDirectiveDBTest.php [hunk 23]
```diff
@@ -0,0 +1,140 @@
...
+    {
+        $user = new User();
+        $user->name = UserPolicy::ADMIN;
+        $this->be($user);
+
+        $user = factory(User::class)->create();
+
+        $this->schema = /** @lang GraphQL */ '
+        type Query {
+            user(id: ID @whereKey): User
```
Comment (spawnia) [inline tests/Integration/Auth/CanResolvedDirectiveDBTest.php:113]:
```suggestion
            user(id: ID! @whereKey): User
```

File: tests/Unit/Auth/CanDirectiveTestBase.php [hunk 24]
```diff
@@ -0,0 +1,176 @@
...
+        ';
+    }
+
+    public function testThrowsIfNotAuthorized(): void
+    {
+        $this->be(new User());
+
+        $this->schema = $this->getSchema('ability: "adminOnly"');
+
+        $this->graphQL($this->getQuery())->assertGraphQLErrorMessage(AuthorizationException::MESSAGE);
```
Comment (spawnia) [inline tests/Unit/Auth/CanDirectiveTestBase.php:31]: What I meant by `combining` is not to write this into one line, but rather extracting a function like this:

```php
protected function query(?string $foo = null): TestResponse
{
    return $this->graphQL($this->getQuery(), ['foo' => $foo]);
}
```

File: src/Auth/BaseCanDirective.php (hunk 9 above)
[the remark this answers is not in the document]
Comment (spawnia) [reply src/Auth/BaseCanDirective.php:53]: Are they included though? I think only the `definition()` of instantiable classes will be added.

File: src/Auth/CanResolvedDirective.php (hunk 16 above)
Comment (k0ka) [reply src/Auth/CanResolvedDirective.php:42]: `$modelLike` might be object or array (hash) as well.

Comment (spawnia) [reply src/Auth/CanResolvedDirective.php:42]: `array` is a kind of `iterable`, and I don't think it can be any other `object` - given `Utils::applyEach()` requires an `iterable<Model>` or `Model`.

File: src/Auth/BaseCanDirective.php (hunk 9 above)
[the remark this answers is not in the document]
Comment (k0ka) [reply src/Auth/BaseCanDirective.php]: yep, it turns out only instantiable class `definition()` is included. I moved types definition to `commonTypes()` and included it in `@canFind` definition (as it is alphabetically first one).

File: CHANGELOG.md (hunk 10 above)
Comment (k0ka) [reply CHANGELOG.md]: fixed it everywhere

File: tests/Unit/Auth/CanDirectiveTestBase.php (hunk 24 above)
Comment (k0ka) [reply tests/Unit/Auth/CanDirectiveTestBase.php]: combined it

File: src/Auth/CanResolvedDirective.php (hunk 16 above)
Comment (k0ka) [reply src/Auth/CanResolvedDirective.php:42]: Well, the current code won't allow anything but Eloquent Model or list of it. But `authorize` accepts any type of object or array. I think it's better to change `?Model $model` to just `mixed $model` so at least Doctrine plain objects can be used there. Hashes won't work, but fixing it might be tricky, so we might leave it for the future.

File: src/Auth/BaseCanDirective.php [hunk 25]
```diff
@@ -0,0 +1,157 @@
...
+            }
+        });
+    }
+
+    /**
+     * Authorizes request and resolves the field.
+     *
+     * @param  array<string, mixed>  $args
+     */
+    abstract protected function authorizeRequest(mixed $root, array $args, GraphQLContext $context, ResolveInfo $resolveInfo, callable $resolver, callable $authorize): mixed;
```
Comment (spawnia) [inline src/Auth/BaseCanDirective.php:112]: What is the expected signature for `$resolver` and `$authorize`?

File: src/Auth/CanResolvedDirective.php (hunk 16 above)
Comment (spawnia) [reply src/Auth/CanResolvedDirective.php:42]: Alright, I am fine with accepting `mixed` here. A test with some non-`Model` object would be nice.

**Comment by spawnia** [comment]
Thank you, released with https://github.com/nuwave/lighthouse/releases/tag/v6.27.0.
