### PR TITLE
Handle Scout pagination arguments

### LINKED ISSUE #592: How to use @search directive with scopes
what is the proper way to use scopes with the @search directive. 

if i try to use @search directive with scopes i get the following error:

"debugMessage": "Method Laravel\\Scout\\Builder::NAME_OF_THE_SCOPE does not exist."

it is trying to call the scope method on Scout

### PR DESCRIPTION
**Pull request by xahs**
- [x] Added or updated tests
- [ ] Added Docs for all relevant versions

**Related Issue/Intent**

Resolves #592

**Changes**

```php
// Nuwave\Lighthouse\Schema\Directives\Fields\PaginateDirective

protected function getPaginatedResults(array $resolveArgs, int $page, int $first): LengthAwarePaginator
{
    ...

    if ($query instanceof \Laravel\Scout\Builder) {
        return $query->paginate($first, 'page', $page);
    }

    return $query->paginate($first, ['*'], 'page', $page);
}
```

Please review my test case, it could be simpler I think.

### CODE REVIEW

File: src/Schema/Directives/Fields/PaginateDirective.php [hunk 1]
```diff
@@ -138,6 +138,10 @@ protected function getPaginatedResults(array $resolveArgs, int $page, int $first
             $resolveArgs[3]
         );
 
+        if ($query instanceof \Laravel\Scout\Builder) {
```
Comment (lucasmichot) [inline src/Schema/Directives/Fields/PaginateDirective.php]: Maybe import `\Laravel\Scout\Builder`?

Comment (xahs) [reply src/Schema/Directives/Fields/PaginateDirective.php]: I think that in some scenarios, when we check for an ```instanceof``` common class names like ```Builder```, it seems more readable to put the full namespace. 

```php
if ($query instanceof \Laravel\Scout\Builder) {
    return $query->paginate($first, 'page', $page);
}

if ($query instanceof Builder) {
    return $query->paginate($first, 'page', $page);
}
```

Open for discussion...

Comment (spawnia) [reply src/Schema/Directives/Fields/PaginateDirective.php]: We always import classes in code. In this case aliasing to `ScoutBuilder` should make things more readable.

**Comment by spawnia** [comment]
Great job on this @xahs

Thanks!
