### PR TITLE
Fix for #285 table alias for query

### LINKED ISSUE #285: Dot in table name causing sql error
**Describe the bug**
The dot in table naming in model is causing error. 
```php
class Row extends Model
{
   protected $table = 'schema.table'
}
```
**Expected Output**
```json
{
  "data": {
    "rowById": {
      "id": "6156",
      "student": {
        "id": "1945",
        "rows": {
          "data": [
            {
              "id": "45305",
              "student": {
                "id": "1945"
              }
            },
            {
              "id": "41295",
              "student": {
                "id": "1945"
              }
            },
            {
              "id": "7649",
              "student": {
                "id": "1945"
              }
            }
          ]
        }
      }
    }
  },
  "extensions": []
}
```
**Schema**

```graphql
type Query {
    rowById(id: ID @eq): TrackerDataRow @find(model: "App\\TrackerDataRow")
}

type TrackerDataRow{
    id: ID!
    student: Student! 
}

type Student {
    id: ID!
    rows: [TrackerDataRow!]! @hasMany(type: "paginator" relation:"rows")
}
```
**Query**
```graphql
rowById(id:6156) {
    id
    student{
      id
      rows(count:3) {
        data{
          id
          student {
            id
          }
        }
      }
    }
  }
```

**Output/Logs**
```json
{
  "data": {
    "rowById": {
      "id": "6156",
      "student": {
        "id": "1945",
        "rows": null
      }
    }
  },
  "extensions": [],
  "errors": [
    {
      "message": "SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near \".\"\nLINE 1: ...y \"created_at\" desc limit 3 offset 0) as \"tracker\".\"data_row...\n                                                             ^ (SQL: select * from (select * from \"tracker\".\"data_rows\" where \"tracker\".\"data_rows\".\"student_id\" in (1945) order by \"created_at\" desc limit 3 offset 0) as \"tracker\".\"data_rows\")",
      "locations": [
        {
          "line": 6,
          "column": 7
        }
      ]
    }
  ]
}
```

**Environment**

Lighthouse Version: 2.2-beta.1
Laravel Version: 5.5.42
PHP Version: 7.1.18
DB: PostgreSQL 10.5

**Additional context**
I found that line 117 in file src/Support/DataLoader/QueryBuilder.php is causing the error
```php
$fromExpression = '('.$unitedRelations->toSql().') as '.$baseQuery->grammar->wrap($relatedTable);
```

### PR DESCRIPTION
**Pull request by russam**
**Related Issue(s)**

Dot in table name causing sql error

Resolves #285

**PR Type**

Bugfix

**Changes**

Function returns an alias "schema_table" if table name has a dot, like "schema.table".

### CODE REVIEW

File: src/Support/DataLoader/QueryBuilder.php [hunk 1]
```diff
@@ -230,4 +230,22 @@ protected function loadDefaultWith(Collection $collection)
...
     }
+    
+    /**
+     * Get alias for a table name.
+     *
+     * @param string $name
+     *
+     * @return string
+     */
+    private function tableAlias($name)
```
Comment (spawnia) [inline src/Support/DataLoader/QueryBuilder.php]: Add string type hints both for the input and output please
