### PR TITLE
Fix TTL for subscriptions

### LINKED ISSUE #1684: TTL breaks subscriptions
**Describe the bug**

When setting a TTL for subscriptions, following exception is thrown:
```
Redis::set() expects at most 3 parameters, 4 given
```

**Expected behavior/Solution**

**Steps to reproduce**

1. Set the subscription TTL
2. Create a subscription

**Lighthouse Version**

5.0.2

### PR DESCRIPTION
**Pull request by alberthaff**
- [ ] Added or updated tests
- [ ] Documented user facing changes
- [x] Updated CHANGELOG.md

Resolves #1684 

**Changes**

When creating a subscription, following exception was thrown:

`Redis::set() expects at most 3 parameters, 4 given`

Phpredis seems to [support simply appending the TTL in seconds](https://github.com/phpredis/phpredis#examples-4). 

Reduced arguments from 4 to 3, by removing "EX" from the Redis-command.

**Breaking changes**

### CODE REVIEW

**Comment by spawnia** [comment]
@thekonz since you are the author of this implementation, can you give a quick review?

File: src/Subscriptions/Storage/RedisStorageManager.php [hunk 1]
```diff
@@ -97,8 +97,8 @@ public function storeSubscriber(Subscriber $subscriber, string $topic): void
         $this->connection->command('set', array_merge([
             $this->channelKey($subscriber->channel),
             $this->serialize($subscriber),
-            // ...and set the EX option to set the ttl in one command.
-        ], $this->ttl ? ['EX', $this->ttl] : []));
+            // ...and set the TTL in one command.
+        ], $this->ttl ? [$this->ttl] : []));
```
Comment (spawnia) [inline src/Subscriptions/Storage/RedisStorageManager.php:101]: My guess is that this should have been `['EX' => $this->ttl]`. Do we have a test case to cover this?

**Comment by thekonz** [comment]
Ah damn, I think I missed that. ;)

I looked at https://redis.io/commands/set where it shows this example:
grafik

I assumed it would just build the command string like `SET key value EX ttl`, but it sends it to Redis::set first, which takes the ttl simply as a third argument.

@alberthaff good catch!

File: src/Subscriptions/Storage/RedisStorageManager.php (hunk 1 above)
Comment (thekonz) [reply src/Subscriptions/Storage/RedisStorageManager.php:101]: No, explanation in the comment. 'ex' => ttl is a common syntax (so good guess^^), but would break the code aswell, because in \Illuminate\Redis\Connections\Connection::command the framework uses array spread to pass parameters and that does not work for associative arrays.

**Review by thekonz — COMMENTED** [review]
could also be this:
```
        $this->connection->command('set', [
            $this->channelKey($subscriber->channel),
            $this->serialize($subscriber),
            $this->ttl
        ])
```

but works fine either way

**Review by thekonz — DISMISSED** [review]

File: src/Subscriptions/Storage/RedisStorageManager.php (hunk 1 above)
Comment (thekonz) [reply src/Subscriptions/Storage/RedisStorageManager.php:101]: You could do `[ 'key', 'value', ['ex' => $ttl] ]` (double wrapping the 'ex' part) techincally to set more options for the timeout, because Redis::set also can take arguments like this:

```php
// Will set the key, if it doesn't exist, with a ttl of 10 seconds
$redis->set('key', 'value', ['nx', 'ex' => 10]);

// Will set a key, if it does exist, with a ttl of 1000 milliseconds
$redis->set('key', 'value', ['xx', 'px' => 1000]);
```

**Comment by spawnia** [comment]
> could also be this:
> 
> ```
>         $this->connection->command('set', [
>             $this->channelKey($subscriber->channel),
>             $this->serialize($subscriber),
>             $this->ttl
>         ])
> ```
> 
> but works fine either way

This seems much simpler!

File: src/Subscriptions/Storage/RedisStorageManager.php (hunk 1 above)
Comment (thekonz) [reply src/Subscriptions/Storage/RedisStorageManager.php:101]: > Do we have a test case to cover this?

I guess I did not add a ttl when integration testing.

**Comment by alberthaff** [comment]
Changed it to your suggestion @thekonz . Thanks! 👍

**Comment by spawnia** [comment]
What's up with that test failure though?

**Comment by thekonz** [comment]
That's because RedisStorageManagerTest::testStoreSubscriber expects the command to be run without the null at the end. Before the change, there was no third item in the array.
Just add it to the test assertion.

```php
        $redisConnection->expects($this->exactly(2))
            ->method('command')
            ->withConsecutive(
                ['sadd', [
                    'graphql.topic.some-topic',
                    'private-lighthouse-foo',
                ]],
                ['set', [
                    'graphql.subscriber.private-lighthouse-foo',
                    'C:41:"Tests\Utils\Subscriptions\DummySubscriber":57:{'.\Safe\json_encode([
                        'channel' => 'private-lighthouse-foo',
                        'topic' => 'some-topic',
                    ]).'}',
                    null, // <- right here
                ]]
            );
```

**Review by spawnia — APPROVED** [review]

**Comment by alberthaff** [comment]
Ah, sorry. Didn't notice until now. Thanks for the fix.
