### PR TITLE
Consider `@rename` when picking the value of a key in `@cache`

### LINKED ISSUE #2152: @cacheKey with @rename not working
**Describe the bug**

The `@cachekey` is not working with `@rename`.

**Expected behavior/Solution**

Work with it.

**Failure test**

```
public function testCacheKeyWithRenameDirective(): void
    {
        $this->mockResolver([
            'id' => 1,
            'name' => 'foobar',
            'email_name' => 'foo@bar.com',
        ]);

        $this->schema = /** @lang GraphQL */ '
        type User {
            id: ID!
            name: String @cache
            emailName: String @cacheKey @rename(attribute: "email_name")
        }

        type Query {
            user: User @mock
        }
        ';

        $response=$this->graphQL(/** @lang GraphQL */ '
        {
            user {
                name
            }
        }
        ')->assertJson([
            'data' => [
                'user' => [
                    'name' => 'foobar',
                ],
            ],
        ]);

        $this->assertSame('foobar', $this->cache->get('lighthouse:User:foo@bar.com:name'));
    }
```

**Output/Logs**

<details><summary>Click to expand</summary>

```
Failed asserting that null is identical to 'foobar'.
```

</details></br>

**Lighthouse Version**

5.51.0

### PR DESCRIPTION
**Pull request by mostafa-rz**
- [X] Added or updated tests
- [x] Documented user facing changes
- [X] Updated CHANGELOG.md

Resolves #2152 

**Changes**

If `@rename` exist use the attribute value as the cacheKey.

**Breaking changes**

no.

### CODE REVIEW

File: src/Schema/Values/TypeValue.php [hunk 1]
```diff
@@ -48,6 +48,10 @@ public function getTypeDefinition(): TypeDefinitionNode
         return $this->typeDefinition;
     }
 
+    /**
+     * @throws DefinitionException
+     * @throws \Exception
+     */
```
Comment (spawnia) [inline src/Schema/Values/TypeValue.php:54]:
```suggestion
```

File: src/Schema/Values/TypeValue.php [hunk 2]
```diff
@@ -71,7 +75,11 @@ public function cacheKey(): ?string
             // First priority: Look for a field with the @cacheKey directive
             foreach ($fieldDefinitions as $field) {
                 if (ASTHelper::hasDirective($field, CacheKeyDirective::NAME)) {
-                    return $this->cacheKey = $field->name->value;
+                    $renameDirectiveNode = ASTHelper::directiveDefinition($field, 'rename');
+
+                    return $renameDirectiveNode
+                        ? $this->cacheKey = ASTHelper::directiveArgValue($renameDirectiveNode, 'attribute')
+                        : $this->cacheKey = $field->name->value;
```
Comment (spawnia) [inline src/Schema/Values/TypeValue.php:82]: The assignment can be outside of the ternary and thus not duplicated.

**Review by spawnia — CHANGES_REQUESTED** [review]
Consider the other case in `TypeValue::cacheKey()` (it using a field of type `ID`), it has the same problem and should also be changed work with `@rename`.

File: src/Schema/Values/TypeValue.php [hunk 3]
```diff
@@ -71,7 +71,11 @@ public function cacheKey(): ?string
             // First priority: Look for a field with the @cacheKey directive
             foreach ($fieldDefinitions as $field) {
                 if (ASTHelper::hasDirective($field, CacheKeyDirective::NAME)) {
-                    return $this->cacheKey = $field->name->value;
+                    $renameDirectiveNode = ASTHelper::directiveDefinition($field, 'rename');
+
+                    return $this->cacheKey = $renameDirectiveNode
+                        ? ASTHelper::directiveArgValue($renameDirectiveNode, 'attribute')
+                        : $field->name->value;
```
Comment (spawnia) [inline src/Schema/Values/TypeValue.php:78]: This code is duplicated and can be extracted to a function:

```suggestion
                    return $this->useFieldAsCacheKey($field);
```

**Review by spawnia — CHANGES_REQUESTED** [review]

File: src/Schema/Values/TypeValue.php [hunk 4]
```diff
@@ -71,7 +71,7 @@ public function cacheKey(): ?string
             // First priority: Look for a field with the @cacheKey directive
             foreach ($fieldDefinitions as $field) {
                 if (ASTHelper::hasDirective($field, CacheKeyDirective::NAME)) {
-                    return $this->cacheKey = $field->name->value;
+                    return ASTHelper::getFieldName($field);
```
Comment (spawnia) [inline src/Schema/Values/TypeValue.php:74]:
```suggestion
                    return $this->cacheKey = ASTHelper::internalFieldName($field);
```

File: src/Schema/Values/TypeValue.php [hunk 5]
```diff
@@ -84,7 +84,7 @@ public function cacheKey(): ?string
                     && $fieldType->type instanceof NamedTypeNode
                     && 'ID' === $fieldType->type->name->value
                 ) {
-                    return $this->cacheKey = $field->name->value;
+                    return ASTHelper::getFieldName($field);
```
Comment (spawnia) [inline src/Schema/Values/TypeValue.php:87]:
```suggestion
                    return $this->cacheKey = ASTHelper::internalFieldName($field);
```

File: src/Schema/AST/ASTHelper.php [hunk 6]
```diff
@@ -412,4 +412,13 @@ public static function modelName(Node $definitionNode): ?string
 
         return null;
     }
+
+    public static function getFieldName(FieldDefinitionNode $field): string
```
Comment (spawnia) [inline src/Schema/AST/ASTHelper.php:416]:
```suggestion
    public static function internalFieldName(FieldDefinitionNode $field): string
```

File: CHANGELOG.md [hunk 7]
```diff
@@ -9,6 +9,10 @@ You can find and compare releases at the [GitHub release page](https://github.co
 
 ## Unreleased
 
+### Fixed
+
+- Allow `@cacheKey` with `@rename` https://github.com/nuwave/lighthouse/pull/2155
```
Comment (spawnia) [inline CHANGELOG.md:14]:
```suggestion
- Consider `@rename` to pick the value of a key in `@cache` https://github.com/nuwave/lighthouse/pull/2155
```
